train: /home/yolov8-cellface/analysis/patch_pipeline/yolov8_train_patch/v4_yolov8-seg/train
val: /home/yolov8-cellface/analysis/patch_pipeline/yolov8_train_patch/v4_yolov8-seg/valid

nc: 3
names: ['RBC', 'WBC', 'PLT']